# 主要内容
Numpy是python科学计算的基础包，后面讲的Pandas包括scipy都是在numpy上建立的。numpy是没有提供高级的数据分析功能。

## 内容1
1. numpy的主要对象是同种元素的多维数组，就像是大数据的容器
2. numpy的数组类被称为ndarray


In [1]:
import numpy as np  # 引入numpy

In [2]:
a = np.arange(10) # 一维数组

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(10).reshape(2,5)

In [5]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
a = np.arange(24).reshape(2,3,4)

In [7]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 通过list创建数组
1. [] this is a list
2. 数组包含数组

In [9]:
a =  np.array([1,2,3])

In [10]:
a

array([1, 2, 3])

In [11]:
a = np.array([[1,2],[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
a.ndim  # 判断数组维度

2

In [14]:
a.shape # 判断数组的形状

(2, 2)

In [15]:
b = np.zeros(10) # 浮点数的类型

In [16]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
b.dtype # 判断数组的类型

dtype('float64')

In [18]:
# 转化类型 .astype
b.astype('int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##  索引与切片

In [20]:
a = np.arange(10)

In [21]:
a[5]

5

In [22]:
a[5:8]= 188 # 广播 

In [23]:
a

array([  0,   1,   2,   3,   4, 188, 188, 188,   8,   9])

In [26]:
b = a[5:8].copy()  # 复制数组

In [27]:
b

array([188, 188, 188])

In [29]:
a = np.arange(24).reshape(2,3,4)

In [30]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a[0][0]

array([0, 1, 2, 3])

In [32]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
a[1][2][2]

22

In [37]:
# 使用 ： 代表全部元素
a[1,1,:]

array([16, 17, 18, 19])

##  bool型索引

In [39]:
a = np.random.randn(3,4)  # 生成正态分布随机数

In [40]:
a

array([[-1.38412981, -2.07378174,  2.49369885,  0.2101465 ],
       [-1.68203126,  1.05444578,  0.24741082, -1.27003982],
       [-0.62469077, -0.24684347, -1.26409185,  1.77144353]])

In [42]:
a[a>0]   把所有的bool型给选取出来

array([2.49369885, 0.2101465 , 1.05444578, 0.24741082, 1.77144353])

In [43]:
a

array([[-1.38412981, -2.07378174,  2.49369885,  0.2101465 ],
       [-1.68203126,  1.05444578,  0.24741082, -1.27003982],
       [-0.62469077, -0.24684347, -1.26409185,  1.77144353]])

In [44]:
a[a<0] = 0

In [45]:
a

array([[0.        , 0.        , 2.49369885, 0.2101465 ],
       [0.        , 1.05444578, 0.24741082, 0.        ],
       [0.        , 0.        , 0.        , 1.77144353]])

In [46]:
a = np.random.normal(size=(3,4)) # 标准正态分布随机数

In [47]:
a

array([[ 0.62783709, -2.05455437,  2.28000612,  1.47851682],
       [-1.80024474, -1.20660454, -0.24974684, -2.28539485],
       [ 0.73533946,  0.46148851, -0.45098848,  0.55228267]])

In [48]:
a = np.random.randint(1,5,(3,4))

In [49]:
a

array([[1, 1, 1, 2],
       [2, 2, 1, 2],
       [1, 2, 1, 1]])