# numpy的运算与通用函数
1. reshape方法，改变数组的形状
2. .T是转置的功能
3. 数组的运算有广播的特性，例如a*NUM
4. 平方根，.sqrt()
5. 绝对值，abs()
6. 求数组的和， sum()
7. np.maximum（a, b） 取两个元素的最大值
8. 实例方法，mean,sumS
9. 对列和行进行计算，对行的话a.sum(axis = 1) ,对列的话a.sum(axis = 0)
10. cumsum，是累加  
11. cumprod，累乘
12. bool值是能够相加的
13. 数组排序 .sort
14. 条件运算，np.where(comd, X, Y)
15. 唯一值，np.unique(a)
15. a.max 最大值
16. a.min
17. np.save()

In [6]:
import numpy as np

In [7]:
a = np.arange(10).reshape(2,5)

In [8]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [10]:
a * 5

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [11]:
a + a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [12]:
np.abs(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
np.abs(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
a.sum()

45

In [15]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [16]:
a.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [17]:
c = np.array([True, False, True, False, True, False, True, False])

In [18]:
c

array([ True, False,  True, False,  True, False,  True, False])

In [19]:
c.sum()

4

In [20]:
d = np.random.randn(2,5)

In [21]:
d

array([[ 1.31442858,  0.48762724, -0.19540432,  0.31057623,  0.73724913],
       [-1.51570543,  0.17042769, -1.9901789 , -0.11702234,  0.29517808]])

In [22]:
np.sort(d)

array([[-0.19540432,  0.31057623,  0.48762724,  0.73724913,  1.31442858],
       [-1.9901789 , -1.51570543, -0.11702234,  0.17042769,  0.29517808]])

In [24]:
cond =  np.array([True, False, True, False])
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

In [25]:
e = np.where(cond,X,Y)

In [26]:
e

array([1, 6, 3, 8])